### Practice

In [539]:
begin_word = "same",
end_word = "cost",
word_list = ["same","came","case","cast","lost","last","cost"]

In [547]:
string = 'carra'
def perm_palindrome(string):
    string = string.lower().replace(' ','')
    
    n = len(string)
    mid = idx = n//2 
    
    if n%2==0:
        idx = mid-1
    
    for i, j in zip(range(0,mid), range(n-1, idx, -1)):
            if string[i]!=string[j]:
                return False
            
    return True
perm_palindrome(string)

False

In [548]:
coordinates = [(0, 1), (1, 3), (2, 2), (3, 4), (4, 6), (5, 5), (6, 7), (7, 9), (8, 8), (9, 10), 
               (10, 12), (11, 11), (12, 13), (13, 15), (14, 14), (15, 16), (16, 18), (17, 17), (18, 19)]

In [ ]:
y = mx + c

In [ ]:
def init_betas(coordinates):
    betas = len(coordinates[0])-1
    beta = []
    intercept = np.random.random()
    for i in betas:
        init_beta.append(np.random.random())
    return intercept, beta


def prediction(coordinates):
    intercept, beta = init_betas(coordinates)
    total_feat = len(coordinates[0])-1
    records = len(coordinates)
    
    d_error = 0
    
    for tup in coordinates:
        pred = intercept
        for i in range(0, total_feat):
            pred += beta[i]*tup[i]
        
        d_error += 2*(tup[total_feat]-pred)/n
    return d_error

def update_betas(old_betas, error):
    old_betas
            
def gradient_descent(coordinates):
    

In [526]:
friends_added = [
    {'user_ids': [1, 2], 'created_at': '2020-01-01'},
    {'user_ids': [3, 2], 'created_at': '2020-01-02'},
    {'user_ids': [2, 1], 'created_at': '2020-02-02'},
    {'user_ids': [4, 1], 'created_at': '2020-02-02'}]

friends_removed = [
    {'user_ids': [2, 1], 'created_at': '2020-01-03'},
    {'user_ids': [2, 3], 'created_at': '2020-01-05'},
    {'user_ids': [1, 2], 'created_at': '2020-02-05'}]

In [529]:
friendship_timeline(friends_added, friends_removed)

[{'user_ids': [1, 2], 'start_date': '2020-01-01', 'end_date': '2020-01-03'},
 {'user_ids': [2, 3], 'start_date': '2020-01-02', 'end_date': '2020-01-05'},
 {'user_ids': [1, 2], 'start_date': '2020-02-02', 'end_date': '2020-02-05'}]

In [528]:
def get_userid(list_users):
    friend_1 = list_users[0]
    friend_2 = list_users[1]
    if friend_1 > friend_2:
        list_users[0], list_users[1] = list_users[1], list_users[0]
    return list_users

def friendship_timeline(friends_added, friends_removed):
    seen_idx = []
    friendships = []
    for created_idx in range(len(friends_added)):
        
        user_id = get_userid(friends_added[created_idx]['user_ids']) 
        date_friends = friends_added[created_idx]['created_at']
        
        for removed_idx in range(len(friends_removed)):
            if removed_idx not in seen_idx:
                id_removed = get_userid(friends_removed[removed_idx]['user_ids'])
                date_removed = friends_removed[removed_idx]['created_at']
                
                if  id_removed == user_id and date_friends <= date_removed:
                    dict_ = {}
                    dict_['user_ids'] = user_id
                    dict_['start_date'] = date_friends
                    dict_['end_date'] = date_removed
                    friendships.append(dict_)
                    seen_idx.append(removed_idx)
                    break
    return friendships
                    

### 31
Longest Common Subsequence <br>

In [35]:
def longestCommonSubSeq(seq1, seq2):
    n = len(seq1)
    m = len(seq2)
    ## Creating a matrix with rows = len(seq2)+1 and columns=len(seq1)+1
    #### First row and column all values = 0
    K = [[(0 if i==0 else j) for j in range(0,n+1)] for i in range(0,m+1)]
    
    ## Go over the elements and start filling the matrix
    for i in range(0,m):
        for j in range(0,n):
            if seq2[i]==seq1[j]:
                K[i+1][j+1] = K[i][j]+1 
            else:
                K[i+1][j+1] = max(K[i+1][j], K[i][j+1])
    
    ## length of the sequence
    lenLongSeq = K[m][n]
    
    ## Finding the sequence
    i = m  # num rows
    j = n # num columns

    longSeq = ''
    currentChar = K[i][j]

    while j>0 and i>0:
        if currentChar == max(K[i][j-1],K[i-1][j]):
            if currentChar == K[i][j-1]:
                currentChar = K[i][j-1]
                j-=1
            else:
                currentChar = K[i-1][j] 
                i-=1
        else:
            currentChar = K[i-1][j-1]
            longSeq = seq1[j-1]+longSeq
            i-=1
            j-=1
   
    return lenLongSeq, longSeq

sequence1 = 'abcdaf'
sequence2 = 'acbcf'
longestCommonSubSeq(sequence1, sequence2)

(4, 'abcf')

### 32
Longest increasing Subsequence <br>
[10, 22, 9, 33, 21, 50, 41, 60, 80] <br>
The longest increasing subsequence (LIS) is [10, 22, 33, 50, 60, 80].

In [32]:
## Using DP

## Logic
##  Create an array-lis with the length of sequence
# Lis stores the length of longest common sub-sequence ending at the index of given item in the array

def longestIncSub(seq):
    if seq:
        n = len(seq)
        arr = [1]*n

        ## Fill the array with the length of longest increasing sequence at each step
        i = 1
        while i<n:
            j = 0
            while j<i:
                if seq[i]>seq[j]:
                    arr[i] = max(arr[j]+1, arr[i])
                j+=1
            i+=1

        ## length of longest increasing sequence
        max_count = 0
        for i in arr:
            if i>max_count:
                max_count=i
        
        ## longest increasing sequence
        lis = []
        i = 1
        while i<=max_count:
            lis.append(seq[arr.index(i)])
            i+=1
        
        return lis, max_count
    return 'invalid input'

sequence = [10, 22, 9, 33, 21, 50, 11, 60, 80]
longestIncSub(sequence)

([10, 22, 33, 50, 60, 80], 6)

In [33]:
seq1 = [90, 22, 9, 33, 21, 50, 41, 60, 80]
longestIncSub(seq1)

([90, 33, 50, 60, 80], 5)

### 33
KnapSack (0/1)<br>

- val = [60, 100, 120] 
- wt = [10, 20, 30] 
- W = 50

In [481]:
max_wt = 7
wtArr =  [1,3,4,5]
valArr = [1,4,5,7]

def knapSack(wt, val, max_weight):
    m = len(wt)

    K = [[0 for j in range(0,max_weight+1)] for i in range(0,m)]

    # iterating over the rows - the actual weights
    for i in range(0, m):
        for j in range(1,max_weight+1):
            if wt[i]<=j:
                K[i][j] = max(val[i]+K[i-1][j-wt[i]], K[i-1][j])
            else:
                K[i][j] = K[i-1][j]
                
    # find the elements that that were selected
    row = m-1
    col = max_weight
    
    knapSackItems = []
    
    while row>0 and col>0:
        if K[row][col] == K[row-1][col]:
            row-=1
        else:
            knapSackItems.append((wt[row], val[row]))
            col-=wt[row] 
            row-=1
    
    return K[m-1][max_weight], knapSackItems, K
            
knapSack(wtArr, valArr, max_wt)

(9,
 [(4, 5), (3, 4)],
 [[0, 1, 1, 1, 1, 1, 1, 1],
  [0, 1, 1, 4, 5, 5, 5, 5],
  [0, 1, 1, 4, 5, 6, 6, 9],
  [0, 1, 1, 4, 5, 7, 8, 9]])

In [90]:
knapSack(wt = [10, 20, 30], val = [60, 100, 120], max_weight = 50)

(220, [(30, 120), (20, 100)])

### 34
Binary Search <br>
Return the index of a number to be searched in a sorted array<br>
Searching a sorted array. Time taken is proportional to log(n)<br>
One variation will always give the first occurence of an element we are searching for and second variation will always give the last occurence of an element we are searching for

In [135]:
### Using recursion
def binary(arr, left, right, num):
    if right>=left:
        n = right-left+1
        mid  = n//2

        if arr[mid+left] == num:
            return mid+left

        elif arr[mid+left] > num:
            return binary(arr, left, mid+left-1, num)

        else:
            return binary(arr, mid+left+1, right, num)

    return 99999

arr = [2,4,10,10,10,18,20]; r = len(arr)-1; l = 0
print(binary(arr,l,r,10))

arr = [1,1,3,3,5,5,5,5,5,9,9,11]; r = len(arr)-1; l = 0
print(binary(arr,l,r,11))

3
11


In [145]:
## iterative approach

# keep dividing the array and search to the left or right based on the result at each step
# for second variation, simply change high=mid-1 to low=mid+1 inside if condition

def binary(arr,num):
    left = 0
    right = len(arr)-1
    idx = -1
    
    while left <= right:
        mid = right+left//2
        if arr[mid]==num:
            idx = mid # we have got the number at an index, storing that to result
            right = mid-1 #trying to see if we have same number before this occurence
            #return mid  returning mid directly would not always return the first occurence
        elif num<arr[mid]:
            right = mid-1
        else:
            left = mid+1
    # we will return the lowest index of the number that we're searching for
    return idx

arr = [2,4,10,10,10,18,20]
print(binary(arr,10))

arr = [1,1,3,3,5,5,5,5,5,9,9,11]
print(binary(arr, 11))

2
11


### 35

#### Iterable and Groupby<br>

Syntax: itertools.groupby(iterable, key_func)

Parameters:
iterable: Iterable can be of any kind (list, tuple, dictionary).
key: A function that calculates keys for each element present in iterable.

Return type: It returns consecutive keys and groups from the iterable. If the key function is not specified or is None, key defaults to an identity function and returns the element unchanged.

##### Lists(mutable), tuple(immutable), dictionary(mutable) - All support indexing but all don't support assignment

In [321]:
## Example-1

import itertools

L = [("a", 1), ("a", 2), ("b", 3), ("b", 4)]
  
# Key function
key_func = lambda x: x[0]
  
for key, group in itertools.groupby(L, key_func):
    print(key + " :", list(group))

a : [('a', 1), ('a', 2)]
b : [('b', 3), ('b', 4)]


In [323]:
## Example-2
a_list = [("Animal", "cat"), ("Animal", "dog"), ("Bird", "peacock"), ("Bird", "pigeon")]

an_iterator = itertools.groupby(a_list, lambda x : x[0])
  
for key, group in an_iterator:
    key_and_group = {key : list(group)}
    print(key_and_group)

{'Animal': [('Animal', 'cat'), ('Animal', 'dog')]}
{'Bird': [('Bird', 'peacock'), ('Bird', 'pigeon')]}


#### Big O

- Big O notation describes how quickly runtime will grow relative to the input as the input gets arbitrarily large
- We compare how quickly runtime grows, and not compare exact times, since those can very depending on hardware
- Big O can be used in time and in memory

- Horrible : O(n!), O(2^n) - Exponential, O(n^2) - quadratic<br>
- Bad : O(n log n) - Log Linear <br>
- Fair : O(n) - Linear<br>
- Good : O(log n) - Logarithmic, O(1) - Constant <br>

- n^3 - Cubic  <br>
Neural Networks have cubic and quadratic run times, that's where GPUs come in handy

#### Questions

1. list = [1,2,3]; list[0]
Big(O) here is 1 and will remain 1 no matter how long the list becomes. Why?

2. For a for loop printing the values in this list, will have Big(0) - O(n) Why?

3. Nested for loop will have quadratic Big(O). Why?


#### Calculation
- We care about only the most significant terms, remember as the i/p grows larger only the faster growing terms will matter, LIKE taking limit towards infinity
- In a function let's say there are 3 for loops, not nested. Its runtime will be 3O(n), still linear. It's not cubic. Also 3(infinity) is no different that infinity, so we can drop 3, and say it's run time is O(n)


#### Space Complexity
- Notation of space complexity is same, but instead it we check the size of allocation of memory rather than time of operation

### 36

Given a list of timestamps in sequential order, return a list of lists grouped by week (7 days) using the first timestamp as the starting point.

Example:

ts = [ '2019-01-01', '2019-01-02', '2019-01-08', '2019-02-01', '2019-02-02', '2019-02-05', ]

output = [ ['2019-01-01', '2019-01-02'], ['2019-01-08'], ['2019-02-01', '2019-02-02'], ['2019-02-05'], ]

In [345]:
import datetime
import itertools

def groupByWeek(arr):
    if arr:
        firstDay = datetime.datetime.strptime(arr[0], '%Y-%m-%d')
        outputList = []
        
        for key, group in itertools.groupby(arr, lambda x: (datetime.datetime.strptime(x, '%Y-%m-%d')-firstDay).days//7):
            outputList.append(list(group))
        
        return outputList
    
inp =  ['2019-01-01', '2019-01-02', '2019-01-08', '2019-02-01', '2019-02-02', '2019-02-05']
groupByWeek(inp)

[['2019-01-01', '2019-01-02'],
 ['2019-01-08'],
 ['2019-02-01', '2019-02-02'],
 ['2019-02-05']]

### 37

- Given a pivot x, and a list lst, partition the list into three parts.
- The first part contains all elements in lst that are less than x 
- The second part contains all elements in lst that are equal to x 
- The third part contains all elements in lst that are larger than x 

Ordering within a part can be arbitrary.

- For example, given x = 10 and lst = [9, 12, 3, 5, 14, 10, 10], one partition may be [9, 3, 5, 10, 10, 12, 14].

In [594]:
## Can be solved using brute force or a linked list

def partitionList(arr, pivot):
    pivot_element = pivot
    partitionIdx = 0
    
    for i in range(0, len(arr)):
        if arr[i]<=pivot_element:
            arr[i], arr[partitionIdx] = arr[partitionIdx], arr[i]
            partitionIdx+=1
    return arr

lst = [9, 12, 3, 10, 5, 14, 10]
partitionList(lst, 5)

[3, 5, 9, 10, 12, 14, 10]

### 38

Median of a streaming data
- Approach:
    - Divide the sorted array into two structures. Now you worry only about the largest value from the first half and smallest value from 2nd half
    - [1,2,3,4,5,6,7]  -> [1,2,3] [4,5,6,7]
    - Heaps does this perfectly well, stores values in this order
    
- Heaps:
    - Binary trees where in min-heap a parent node is always smaller than the children. Smallest number on top
    - All operations in a heap are done in log(n) time as it is a binary tree
    - Heaps is an example of priority queue, say max value on top (max-heap)
    - arr[0] in a heap will always return the smallest element
    
    
- App continued:
    - First array will be a max heap and 2nd array will be a min heap
    - The two structures/heaps should be of same length or the difference should be at max 

In [236]:
## Approach-1
from heapq import heappop, heappush

class MedianFinder:
    def __init__(self):
        self.q1 = []
        self.q2 = []

    def addNum(self, num: int) -> None:
        heappush(self.q1, -num)
        heappush(self.q2, -heappop(self.q1))
        
        if len(self.q2)>len(self.q1):
            heappush(self.q1, -heappop(self.q2))
    def findMedian(self) -> float:
        if len(self.q1)!=len(self.q2):
            return -self.q1[0]
        else:
            return (self.q2[0]-self.q1[0])/2


# Your MedianFinder object will be instantiated and called as such:
# obj = MedianFinder()
# obj.addNum(num)
# param_2 = obj.findMedian()

obj = MedianFinder()
obj.addNum(2)
print(obj.findMedian())
obj.addNum(3)
print(obj.findMedian())
obj.addNum(5)
print(obj.findMedian())
obj.addNum(7)
print(obj.findMedian())

2
2.5
3
4.0


In [237]:
## Approach-2

q1 = []; q2 = []

def medianFinder(num):     
    heappush(q1, -num)
    heappush(q2, -heappop(q1))

    if len(q2)>len(q1):
        heappush(q1, -heappop(q2))
        
    if len(q1)!=len(q2):
        return -q1[0]
    else:
        return (-q1[0]+q2[0])/2
    
print(medianFinder(2))
print(medianFinder(3))
print(medianFinder(5))
print(medianFinder(7))

2
2.5
3
4.0


### 39
Numpy operations and Matrix multiplication 
- Transpose
- Add
- Multiply
- Divide
- Append elements in rows
- Append elements in columns

In [299]:
## Change the datatype from list to array
Y = np.array([[5,8,1,2],
     [6,7,3,0],
     [4,5,9,1]])

In [300]:
## Transpose
Y.T

array([[5, 6, 4],
       [8, 7, 5],
       [1, 3, 9],
       [2, 0, 1]])

In [301]:
X=np.array([0,1])
print(X)
print(X.T)

[0 1]
[0 1]


In [223]:
## Add an element to the matrix
Y = Y+2
Y

array([[ 7, 10,  3,  4],
       [ 8,  9,  5,  2],
       [ 6,  7, 11,  3]])

In [224]:
### Multiply
Y = Y*2
Y

array([[14, 20,  6,  8],
       [16, 18, 10,  4],
       [12, 14, 22,  6]])

In [225]:
## Divide
Y/2

array([[ 7., 10.,  3.,  4.],
       [ 8.,  9.,  5.,  2.],
       [ 6.,  7., 11.,  3.]])

In [229]:
### Important: appending rows
np.append(Y, [[1,2,3,4]], axis=0)

array([[14, 20,  6,  8],
       [16, 18, 10,  4],
       [12, 14, 22,  6],
       [ 1,  2,  3,  4]])

In [309]:
Y

array([[5, 8, 1, 2],
       [6, 7, 3, 0],
       [4, 5, 9, 1]])

In [233]:
Y

array([[14, 20,  6,  8],
       [16, 18, 10,  4],
       [12, 14, 22,  6]])

In [234]:
#### Appending columns
np.append(Y, [[1],[2],[3]], axis=1)

array([[14, 20,  6,  8,  1],
       [16, 18, 10,  4,  2],
       [12, 14, 22,  6,  3]])

#### Matrix Mult

In [238]:
X = [[12,7,3],
     [4,5,6],
     [7,8,9]]

Y = [[5,8,1,2],
     [6,7,3,0],
     [4,5,9,1]]

result = [[sum(a*b for a,b in zip(X_row, Y_col)) for Y_col in zip(*Y)] for X_row in X]
result

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]

In [247]:
a = np.array([[1,3,9]])
b =  np.array([[12,7,3]])

In [248]:
np.dot(a,b.T)

array([[60]])

### 40
Given a dict of dicts of a JSON blob, parse particular entries
- Access the self value for items

In [255]:
json_obj = {
  "items": [
    {
      "id": "12345",
      "links": {
        "self": "https://www.google.com"
      },
      "name": "beast",
      "type": "Device"
    }
  ],
  "links": {
    "self": "https://www.google.com"
  },
  "paging": {
    "count": 1,
    "limit": 1,
    "offset": 0,
    "pages": 1
  }}

json_obj['items'][0]['links']['self']

'https://www.google.com'

### 41
Coding test: moving average Input.    10, 20, 30, 10, ... Output: 10, 15, 20, 17.5, …


In [455]:
class Average:
    def __init__(self):
        self.num_list = []
        self.avg = 0
    
    def average(self, num):
        self.num_list.append(num)
        n = len(self.num_list)        
        if self.avg==0:
            self.avg = num
            return self.avg
        else:
            self.avg = ((n-1)*self.avg + num)/n
            return self.avg

In [456]:
avgg = Average()

In [257]:
arr = []
class Average:
    def __init__(self, num):
        self.arr = arr.append(num)
    def avg(self):
        summ = 0
        n = len(arr)
        for i in arr:
            summ = summ+i
        return summ/n

a = Average(10)
print(a.avg())
a = Average(20)
print(a.avg())
a = Average(30)
a.avg()

10.0
15.0


20.0

### 42
Imagine a barplot, how much water can you pour over it 

Sol: Min(tallest on left, tallest on right) - length of bar for all bars - O(N2)

[5,1,3,4], solution = 4

In [467]:
def find_max(arr):
    if arr:
        max_ = -9999
        for i in arr:
            if i>max_:
                max_ = i
        return max_
    return 0


def solution(arr):
    water = 0
    for idx in range(1,len(arr)-1):
        leftArr = arr[:idx]
        rightArr = arr[idx+1:]
        x =  min(find_max(leftArr), find_max(rightArr)) - arr[idx]
        if x>0:
            water += x
    return water

In [470]:
print(solution([5,1,3,1]))
print(solution([5,1,3,5]))
print(solution([5,1,3,4]))

2
6
4


In [283]:
arr = [5,1,3,4]

def findMinTallest(arr, barIdx):
    ## Max or min cannot be used on a single number i.e. max(arr[0]) but can be used when we have max(arr[0:1]) it's the same thing
    ## but also not
    return min(max(arr[:barIdx]), max(arr[barIdx+1:]))
    
def water(arr):
    arr1 = [1]*(len(arr)-2)
    
    ### We are not interested in the first and last values when doing the calculation, they will be included when calculating min and max 
    # though
    for i in range(1,len(arr)-1):
        arr1[i-1] = findMinTallest(arr, i) - arr[i]
    
    total_water = 0
    for bar in arr1:
        total_water += bar
        
    return total_water

water(arr)

4